os: linux
dist: jammy
services: docker
addons:
  hosts:
    - mariadb.example.com
    - mariadb1.example.com
    - mariadb2.example.com
    - mariadb3.example.com

install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git
  - |-
    if [ -z "$server_branch" ] ; then
      case $TRAVIS_OS_NAME in
        windows)
          connector-test-machine/launch.bat -t "$srv" -v "$v" -d "$DB"
          # Since refreshenv doesn't seem to work, we set this manually
          export WIX="/c/Program Files (x86)/WiX Toolset v3.11"
          ;;
        linux)
          source connector-test-machine/launch.sh -t "$srv" -v "$v" -d "$DB" -l "$local" -c "$CLEAR_TEXT" -p "$packet"
          ;;
      esac
    fi

stages:
  - Minimal
  - Language
  - name: Enterprise
    if: type = push AND fork = false
  - Community
  - Other
  - name: Benchmarks
    if: type = push AND fork = false

jobs:
  fast_finish: true
  allow_failures:
    - env: srv=build
  include:
    - stage: Minimal
      env: srv=mariadb v=10.6 local=1
      name: "CS 10.6"
    - stage: Minimal
      env: srv=mariadb-es v=10.6
      name: "ES 10.6"
      dist: jammy
      if: type = push AND fork = false

    - stage: Enterprise
      env: srv=mariadb-es v=10.5
      name: "ES 10.5"
      dist: jammy
      if: type = push AND fork = false
    - stage: Enterprise
      env: srv=mariadb-es-test v=11.4
      dist: jammy
      name: "ES 11.4 preview"
      if: type = push AND fork = false
    - stage: Enterprise
      env: srv=maxscale
      dist: jammy
      name: "Maxscale"

    - stage: Community
      env: srv=mariadb v=11.4
      os: windows
      language: shell
      name: "CS 11.4 - Windows"
    - stage: Community
      env: srv=mariadb v=10.5 local=1
      dist: bionic
      name: "CS 10.5"
      node_js: 16
    - env: srv=mariadb v=10.11 local=1
      dist: jammy
      name: "CS 10.11"
    - env: srv=mariadb v=11.2 local=1 CLEAR_TEXT=1
      dist: jammy
      name: "CS 11.2"
    - env: srv=mariadb v=11.4 local=1
      dist: jammy
      name: "CS 11.4"
    - env: srv=mariadb v=11.5
      name: "CS 11.5"
    - env: srv=mariadb v=11.6-rc
      name: "CS 11.6"
    - env: srv=mysql v=8.4
      name: "MySQL 8.4"
    - env: srv=mysql v=9.0
      name: "MySQL 9.0"
    - env: srv=build
      name: "CS build"


after_failure:
  - if [ "$srv" == "maxscale" ] ; then docker-compose -f ${COMPOSE_FILE} exec -u root maxscale tail -500 /var/log/maxscale/maxscale.log; fi
