
stages:
  - Minimal
  - name: Enterprise
    if: type = push AND fork = false
  - Community
  - Language
  - Benchmarks

jobs:
  fast_finish: true
  allow_failures:
    - env: srv=build
  include:
    - stage: Minimal
      env: srv=mariadb v=10.6 local=1
      name: "CS 10.6"
    - stage: Minimal
      env: srv=mariadb-es v=10.6
      name: "ES 10.6"
      if: type = push AND fork = false

    - stage: Enterprise
      env: srv=mariadb-es v=10.4
      name: "ES 10.4"
      if: type = push AND fork = false
    - stage: Enterprise
      env: srv=mariadb-es v=10.5
      name: "ES 10.5"
      if: type = push AND fork = false
    - stage: Enterprise
      env: srv=mariadb-es-test v=23.08
      name: "ES 23.08"
      if: type = push AND fork = false
    - stage: Enterprise
      env: srv=maxscale
      name: "Maxscale docker latest"

    - stage: Community
      env: srv=mariadb v=10.6
      os: windows
      language: shell
      name: "CS 10.6 - Windows"
    - stage: Community
      env: srv=mariadb v=10.4 local=1
      dist: bionic
      name: "CS 10.4"
    - stage: Community
      env: srv=mariadb v=10.5 local=1 DISABLE_SSL=1
      dist: bionic
      name: "CS 10.5"
    - env: srv=mariadb v=10.11 local=1
      name: "CS 10.11"
    - env: srv=mariadb v=11.0 local=1
      name: "CS 11.0"
    - env: srv=mariadb v=11.1 local=1
      name: "CS 11.1"
    - env: srv=mariadb v=11.1 local=1
      name: "CS 11.2"
    - env: srv=mariadb v=11.2 local=1
      name: "CS 11.3"
    - env: srv=mysql v=5.7
      name: "MySQL 5.7"
    - env: srv=mysql v=8.0
      name: "MySQL 8.0"
    - env: srv=build
      name: "CS build"