version: '2.1'
services:
  db:
    image: $TYPE_VERS
    command: --max-connections=500 --max-allowed-packet=20M --innodb-log-file-size=200M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key --bind-address=0.0.0.0 --performance-schema=ON $ADDITIONAL_CONF
    ports:
      - 3305:3306
    volumes:
      - /tmp/ssl:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
      - $ENTRYPOINT:/es-initdb.d
      - $ENTRYPOINT_PAM:/pam
    environment:
      MARIADB_USER: boby
      MARIADB_PASSWORD: heyPassw0@rd
      MARIADB_DATABASE: $TEST_DB_DATABASE
      MYSQL_DATABASE: $TEST_DB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysql", "--protocol=tcp", "-uboby", "-h127.0.0.1", "--password=heyPassw0@rd"]
      timeout: 20s
      retries: 10