version: '2.1'
services:
  db:
    image: mariadb:10.5
    command: --max-connections=500 --max-allowed-packet=20m --innodb-log-file-size=200M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key --bind-address=0.0.0.0
    ports:
      - 3305:3306
    volumes:
      - /tmp/ssl:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
      - $ENTRYPOINT_PAM:/pam
    environment:
      MYSQL_DATABASE: $TEST_DB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysql", "--protocol=tcp", "-uboby", "-h127.0.0.1", "--password=heyPassw0@rd"]
      timeout: 20s
      retries: 10

  maxscale:
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"
    ports:
      - 4006:4006
      - 4008:4008
      - 4009:4009
    volumes:
      - /tmp/ssl:/etc/sslcert
    build:
      context: .
      dockerfile: maxscale/Dockerfile
      args:
        MAXSCALE_VERSION: 2.5.8
